using Microsoft.AspNetCore.Authorization;using Microsoft.AspNetCore.Mvc;using Google.Cloud.Firestore;using UserHub.DTOs;using UserHub.Models;
namespace UserHub.Controllers;
[ApiController][Route("api/[controller]")][Authorize] public class ReportController:ControllerBase{readonly FirestoreDb db;public ReportController(FirestoreDb db)=>this.db=db;string Uid()=>User.FindFirst("user_id")?.Value??User.FindFirst("sub")?.Value??throw new UnauthorizedAccessException();async Task<AppUser?> Profile(){var s=await db.Collection("users").Document(Uid()).GetSnapshotAsync();return s.Exists?s.ConvertTo<AppUser>():null;}
[HttpGet]public async Task<IEnumerable<PowerOutageReport>> All(){var p=await Profile();if(p?.Role!="administrador")return [];var s=await db.Collection("reports").GetSnapshotAsync();return s.Documents.Select(d=>d.ConvertTo<PowerOutageReport>());}
[HttpGet("mine")]public async Task<IEnumerable<PowerOutageReport>> Mine(){var s=await db.Collection("reports").WhereEqualTo("CiudadanoId",Uid()).GetSnapshotAsync();return s.Documents.Select(d=>d.ConvertTo<PowerOutageReport>());}
[HttpGet("zone/{zonaId}")]public async Task<IEnumerable<PowerOutageReport>> Zone(string zonaId){var s=await db.Collection("reports").WhereEqualTo("ZonaId",zonaId).GetSnapshotAsync();return s.Documents.Select(d=>d.ConvertTo<PowerOutageReport>()).Where(r=>r.Estado!="resuelto");}
[HttpPost]public async Task<ActionResult<PowerOutageReport>> Create(CreateReportDto dto){var active=await db.Collection("reports").WhereEqualTo("ZonaId",dto.ZonaId).GetSnapshotAsync();var duplicate=active.Documents.Select(d=>d.ConvertTo<PowerOutageReport>()).FirstOrDefault(r=>r.Estado!="resuelto");if(duplicate is not null)return Conflict(new{message="Ya existe un reporte activo en esta zona.",report=duplicate});var r=new PowerOutageReport{Id=Guid.NewGuid().ToString("N"),ZonaId=dto.ZonaId,Direccion=dto.Direccion,HoraInicio=dto.HoraInicio,Estado="nuevo",EvidenciaUrl=dto.EvidenciaUrl,Confirmaciones=1,CiudadanoId=Uid()};await db.Collection("reports").Document(r.Id).SetAsync(r);return Ok(r);}
[HttpPost("{id}/confirm")]public async Task<ActionResult<PowerOutageReport>> Confirm(string id){var rr=db.Collection("reports").Document(id);var s=await rr.GetSnapshotAsync();if(!s.Exists)return NotFound();var r=s.ConvertTo<PowerOutageReport>();var c=await db.Collection("confirmations").WhereEqualTo("ReporteId",id).WhereEqualTo("CiudadanoId",Uid()).GetSnapshotAsync();if(c.Count>0)return Conflict(new{message="Ya confirmaste este reporte."});var conf=new Confirmation{Id=Guid.NewGuid().ToString("N"),ReporteId=id,CiudadanoId=Uid(),Fecha=DateTime.UtcNow};await db.Collection("confirmations").Document(conf.Id).SetAsync(conf);r.Confirmaciones++;if(r.Confirmaciones>=2)r.Estado="confirmado";await rr.SetAsync(r);return Ok(r);}
[HttpGet("assigned")]public async Task<IEnumerable<PowerOutageReport>> Assigned(){var p=await Profile();if(p?.Role!="tecnico")return [];var s=await db.Collection("reports").GetSnapshotAsync();return s.Documents.Select(d=>d.ConvertTo<PowerOutageReport>()).Where(r=>r.Estado!="resuelto");}
[HttpPost("{id}/resolve")]public async Task<ActionResult<PowerOutageReport>> Resolve(string id,ResolveReportDto dto){var p=await Profile();if(p?.Role!="tecnico")return Forbid();var rr=db.Collection("reports").Document(id);var s=await rr.GetSnapshotAsync();if(!s.Exists)return NotFound();var r=s.ConvertTo<PowerOutageReport>();r.Estado="resuelto";r.TecnicoAsignadoId=Uid();await rr.SetAsync(r);var res=new Resolution{Id=Guid.NewGuid().ToString("N"),ReporteId=id,Causa=dto.Causa,HoraRestablecimiento=dto.HoraRestablecimiento,Detalle=dto.Detalle};await db.Collection("resolutions").Document(res.Id).SetAsync(res);return Ok(r);}}
